// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6p0XEpIlvf1blor8jAUofBziTPSDzxq0',
    appId: '1:1015149739396:web:44554f8db77706247971d1',
    messagingSenderId: '1015149739396',
    projectId: 'smarttaxi-4aeb5',
    authDomain: 'smarttaxi-4aeb5.firebaseapp.com',
    databaseURL: 'https://smarttaxi-4aeb5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarttaxi-4aeb5.firebasestorage.app',
    measurementId: 'G-0FVLT1F09N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASz6hYYzZpiMI5spjTqXZg-37esPTcqhs',
    appId: '1:1015149739396:android:2d49a214f550a7407971d1',
    messagingSenderId: '1015149739396',
    projectId: 'smarttaxi-4aeb5',
    databaseURL: 'https://smarttaxi-4aeb5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarttaxi-4aeb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOaEAIBVeEK6UP7nTHTIzMmNzf9Pte0oU',
    appId: '1:1015149739396:ios:3c8a902c3e79cf757971d1',
    messagingSenderId: '1015149739396',
    projectId: 'smarttaxi-4aeb5',
    databaseURL: 'https://smarttaxi-4aeb5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarttaxi-4aeb5.firebasestorage.app',
    iosBundleId: 'com.example.smartTaxiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6p0XEpIlvf1blor8jAUofBziTPSDzxq0',
    appId: '1:1015149739396:web:1ea4a8cf5737b88d7971d1',
    messagingSenderId: '1015149739396',
    projectId: 'smarttaxi-4aeb5',
    authDomain: 'smarttaxi-4aeb5.firebaseapp.com',
    databaseURL: 'https://smarttaxi-4aeb5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarttaxi-4aeb5.firebasestorage.app',
    measurementId: 'G-G4HXW3QE6X',
  );
}
